### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by harmonygeek**

### CODE REVIEW

**Review by GowthamRayar — COMMENTED** [review]
Wearable-reply Review:
======================

1) Add maven dependency in Installaltion instructions with version as 1.0.0
2) Source section is missing in README
3) Sonar quality gate Tag and main.yml tag missing in README

**Review by sharathks84 — APPROVED** [review]
Okay Approved

**Review by Gleelakrishna — COMMENTED** [review]
ok

**Review by Gleelakrishna — APPROVED** [review]
ok

**Pull request merged**
